# 1. Use the official .NET SDK to build the app
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app

# 2. Copy the entire solution (all folders) into Docker
COPY . ./

# 3. Explicitly tell it which project is the main entry point to build
# ⚠️ Check which folder has your Program.cs file! If it's in QuantityMeasurementAPI, change the folder name below:
RUN dotnet publish QuantityMeasurementApp/QuantityMeasurementApp.csproj -c Release -o out

# 4. Create the final lightweight runtime image
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/out .

# Tell Render to listen on port 8080
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

# ⚠️ Make sure this matches the .dll name generated by the publish command
ENTRYPOINT ["dotnet", "QuantityMeasurementApp.dll"]
